---
title: "ussie"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ussie}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ussie)
library(dplyr)
```

The goal of **ussie** is to help you work with European Football League data.
It uses data from the **engsoccerdata** package.

We can create a *matches* tibble using raw data from engsoccerdata:

```{r matches_italy}
matches_italy <- uss_make_matches(engsoccerdata::italy, "Italy")

glimpse(matches_italy)
```

We can also create a matches tibble using a `country`:

```{r get_matches_italy}
get_matches_italy <- uss_get_matches("italy")

glimpse(get_matches_italy)
```

We can add filtering conditions:

```{r matches_filter}
uss_get_matches("italy", season == 1934) |> glimpse()
```

We can get the final results for seasons:

```{r seasons}
italy_seasons <-
  get_matches_italy |>
  uss_make_teams_matches() |>
  uss_make_seasons_final() |>
  glimpse()
```

We can look at the effect of tiers on (wins - losses):

```{r plot}
leeds_norwich <-
  uss_get_matches("england") |>
  uss_make_teams_matches() |>
  dplyr::filter(team %in% c("Leeds United", "Norwich City")) |>
  dplyr::mutate(tier = as.factor(tier)) |>
  uss_make_seasons_final() |>
  dplyr::arrange(team, season)

uss_plot_seasons_tiers(leeds_norwich, wins - losses)
```

